/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminImagesRouteImport } from './routes/admin/images'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin/agents.index'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin/agents.$agentId'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImagesRoute = AdminImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/images': typeof AdminImagesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/articles'
    | '/admin/images'
    | '/admin/login'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/admin/agents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/articles'
    | '/admin/images'
    | '/admin/login'
    | '/admin'
    | '/admin/agents/$agentId'
    | '/admin/agents'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/articles'
    | '/admin/images'
    | '/admin/login'
    | '/admin/'
    | '/admin/agents/$agentId'
    | '/admin/agents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/images': {
      id: '/admin/images'
      path: '/images'
      fullPath: '/admin/images'
      preLoaderRoute: typeof AdminImagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminImagesRoute: typeof AdminImagesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminImagesRoute: AdminImagesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
